### ISSUE TITLE
Add support for userlist/user/group

### ISSUE THREAD

**Issue by mjf** [bse666/voidrice#2]
The content of the [userlist](https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#3.4) section does not render very nicely. Support for `user`/`group` directives would be nice to have too. It would be nice if `insecure-password` content has it's own identifier so that one could configure toggling of visibility of the password in Vim easily.

**Comment by bse666** [comment]
wrong repo?

**Comment by mjf** [comment]
@bse666 Yep. That was for Vim HAProxy configuration syntax highlighting...
